twitter-to-kafka:
  twitter-keywords:
    - Java
    - Kafka
    - Spring
  welcome-message: Hello microservices!
  enable-mock-tweets: true
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000